---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs-nginx
  labels:
    app: nginx
    purpose: svcdemo
spec:
  replicas: 3
  minReadySeconds: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.25
          name: nginx
          ports:
            containerPort: 80
            protocol: TCP