---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: nginx
    env: dev
spec:
  containers:
    - name: hello-pod
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP
    - name: logforwarder
      image: alpine
      args:
        - sleep
        - 1d