---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    purpose: rsdemolike
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
      release: vi.1
  template:
    metadata:
      labels:
        app: jenkins
        release: vi.1
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP